name: Security Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run vulnerability scanner
        run: |
          chmod +x scan.sh
          ./scan.sh
